#
# Treefmt configuration.
#
# https://treefmt.com/latest/getting-started/configure
#

[formatter.cljfmt]
command = "cljfmt"
includes = [
	"*.clj*",
	"*.edn"
]
options = [
	"fix"
]

[formatter.nixfmt]
command = "nixfmt"
includes = [
	"*.nix"
]
